# Generated by Django 4.2.10 on 2024-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0002_uploadfile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='explanation',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('IP', 'In Progress'), ('R', 'Resolved')], default='New', max_length=3),
        ),
    ]
