# Generated by Django 4.2.10 on 2024-03-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0003_uploadfile_explanation_uploadfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='username',
            field=models.CharField(default='anon', max_length=50),
        ),
    ]
