# Generated by Django 4.2.10 on 2024-03-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0005_alter_uploadfile_email_alter_uploadfile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='reason',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
