# Generated by Django 4.2.10 on 2024-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0006_uploadfile_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
