# Generated by Django 4.2.10 on 2024-04-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower', '0008_uploadfile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
